user_token: NmE0YzRjMzEtNTM2Zi00NDY5LThmNzItZTE1YmE2MTZkNGE4XzEwOA==

session:
  key: 466yn87zaiC-LeEtfxuOUU2pSKEB-pRVmJ9vmsJ30G4=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 0.0.0.0
  port: 5432
  user: postgres
  password: postgres
  database: postgres
bot:
  token: 196378a02c47fb84ea4c27a29d0cbe312bf4cd8192d89d9c502446e008de4794d97e3a184fec0ea01532e
  group_id: 206827067
