"""first migration

Revision ID: 0629735fb076
Revises: f87fa8c6efbf
Create Date: 2021-09-12 01:15:43.759330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0629735fb076'
down_revision = 'f87fa8c6efbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answers', ['title'])
    op.create_unique_constraint(None, 'themes', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='unique')
    op.drop_constraint(None, 'answers', type_='unique')
    # ### end Alembic commands ###
