"""first migration

Revision ID: 86f3a2a44206
Revises: 27cfb210e8f0
Create Date: 2021-09-12 04:09:08.488642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f3a2a44206'
down_revision = '27cfb210e8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'questions', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    # ### end Alembic commands ###
